# List available recipes
default:
    @just --list

# Start the development server
dev:
    bun run dev

# Build the Next.js site (regenerates the content collection, then builds)
build:
    bun run build

# Generate the MCP documentation corpus
generate-corpus:
    bun run generate:corpus

# Verify the corpus generator is deterministic (byte-identical reruns)
check-corpus:
    bun run generate:corpus /tmp/corpus-check-a
    bun run generate:corpus /tmp/corpus-check-b
    diff -r /tmp/corpus-check-a /tmp/corpus-check-b
    rm -rf /tmp/corpus-check-a /tmp/corpus-check-b

# Build the corpus as a reproducible Nix package output
build-corpus:
    nix build .#corpus

# Verify bun.nix is in sync with bun.lock (regenerate and diff)
check-bun-nix:
    bun2nix -o /tmp/bun.nix.check
    diff -q bun.nix /tmp/bun.nix.check
    rm -f /tmp/bun.nix.check

# Type-check TypeScript. Depends on `build` for Next's generated route types
# (.next/types).
check-types: build
    bun run types:check

# Run tests
test:
    bun test

# Check formatting (prettier for TS/JSON/MDX, alejandra for Nix). bun.nix is
# autogenerated, so it is excluded.
check-format:
    bun run format:check
    rg --files -g '*.nix' -g '!.*' -g '!bun.nix' | xargs alejandra -c

# Format all code
format:
    bun run format:write
    rg --files -g '*.nix' -g '!.*' -g '!bun.nix' | xargs alejandra

# Lint TypeScript (eslint) and Nix (statix)
lint:
    bun run lint
    rg --files -g '*.nix' -g '!.*' -g '!bun.nix' | xargs -L 1 statix check --

# Run all validation checks. `check-types` pulls in `build` as a dependency.
validate: check-types check-format lint test check-corpus check-bun-nix
